# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a69b14709f2f87f09f7eeb971cf903b85c8968685da0e1751d9cc1a7e2ea4955665b9572f380eab23835de6741002334ced6b3f3bb86d9b78cb26728678540a

test:
  secret_key_base: 27a1335500d40954b1e33fb021f7a11f0991614fe3292a358c6243d0249baee615679c5df82cb1a11698790445291927d776a8ab8741e852a33c846b06fa0cc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
